### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by s9615562**
我是李佩穎
13.115.160.121:3000/api/attractions?page=0&keyword=北
13.115.160.121:3000/api/attractions?page=0
13.115.160.121:3000/api/attraction/2
13.115.160.121:3000/api/mrts

### CODE REVIEW

**Comment by cwpeng** [comment]
Your server is down.

**Comment by s9615562** [comment]
老師我重開putty了，再幫我看一次

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response format of http://13.115.160.121:3000/api/attraction/1 is incorrect.
2. `img` field should be `images`.
3. `img` field contains duplicated images.
4. `lng` and `lat` fields are all the same. It's wrong data obviously.
5. Run your server in the background, so that it can work properly even if you close putty.

Fix issues and re-request review.

**Comment by cwpeng** [comment]
You do not need to close pull request next time, just re-request review. It's helpful to keep track of our conversation.

**Pull request closed without merging**
