### PR TITLE
edit1

### PR DESCRIPTION
**Pull request by s9615562**
老師，我是李佩穎，不好意思我不小心把這禮拜作業merge了，所以又開了新的pull request，請老師再幫我檢查一次，謝謝
http://13.115.160.121:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. There are two separating lines with 1px height and light grey color.
2. In homepage and attraction page, basic text color should be lighter, align with design.
3. Image slider should extend to full width in mobile devices.

**Review by cwpeng — CHANGES_REQUESTED** [review]
There are two separating lines with 1px height and light grey color.

**Comment by s9615562** [comment]
image
老師您好 : two separating lines是否是上面照片中的兩條線嗎? 是的話 是否是上面那條線需要隨著頁面下滑不見?

**Comment by s9615562** [comment]
老師您好:我發現是手機板也需要two separating lines 謝謝老師~

**Comment by cwpeng** [comment]
Your lines are not 1px height with light grey color. Check and align with design carefully.

**Comment by s9615562** [comment]
謝謝老師，這禮拜花了一些時間修資料庫和研究本週功能，之後會看仔細設計稿，再麻煩老師

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
